### ISSUE TITLE
Sellyoursaas Installation and Setup

### ISSUE THREAD

**Issue by pankajxmathur** [DoliCloud/SellYourSaas#91]
**Is your feature request related to a problem? Please describe.**
The Installation and Setup process for Sellyoursaas seems rather cumbersome and elaborate.
Need the ability to have a automated Installation and Setup of Sellyoursaas on Digital Ocean.

**Describe the solution you'd like**
Sellyoursaas should be available via the Digital Ocean Marketplace. A Saas Service provider should be able to search for Sellyoursaas on the Digital Ocean market place and should be able to create a Droplet from there. This will automate the installation and setup of Sellyoursaas Master Node. Similarly there should also be a way to create the Deployment Node in an automated way. The Saas Service Provider should be able to Add Deployment Nodes from the Sellyoursaas GUI interface by pointing to the Deployment Node DNS Name / IP Address.

**Describe alternatives you've considered**
Currently no alternatives are available.

**Additional context**
Refer to the Link - [https://marketplace.digitalocean.com/apps/lamp](url)
<img width="1678" alt="Screenshot 2021-01-06 at 5 12 52 PM" src="https://user-images.githubusercontent.com/833130/103765118-a880a980-5042-11eb-91c0-035c5cd35f41.png">
<img width="1600" alt="Screenshot 2021-01-06 at 5 12 40 PM" src="https://user-images.githubusercontent.com/833130/103765128-ad455d80-5042-11eb-870c-b5372f052fa7.png">

**Comment by eldy** [comment]
Sell-Your-Saas provides a full solution for a 100% automated business. It needs a lot of Open-Source components. Making an automated installation is very difficult and even not possible on most providers because it is not one application but a full system.
This point is not the priority for the moment but i keep the ticket open for future...

**Comment by viapratica** [comment]
Congratulations on the project. I agree that the project has many points that cannot be treated as a package, however, it is very difficult to run the system. In the documentation it is not clear when and where the github files enter. The project seems to be wonderful, but practically impossible to implement and see that I work with web systems since 1999.

**Comment by eldy** [comment]
@viapratica Thanks for feedback. This means we should also enhance the documentation. If you find something not clear in documentation, you mau create another issue with chapter that is not clear so i will complete.
